### ISSUE TITLE
Download on website still refers to previous release

### ISSUE THREAD

**Issue by WenM88** [rcaelers/workrave-website#16]
Hi,
Just wanted to download workrave for Windows, there I noticed the download page referred to 1.10.49 as Latest. While in the Blog 1.10.50 is already announced as newer official release.
Modifying the URL of the link before entering it in the URL-bar indeed gives me the new binary already, so I suppose the website can be updated too?
Regards,
Walter.

**Comment by rcaelers** [comment]
Thanks! Should be fixed now.
